# Build the application from source
FROM golang:1.25.7-trixie AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/app

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=build-stage /go/app /go/app
EXPOSE 5000
USER nonroot:nonroot
ENTRYPOINT ["/go/app"]