# Build the application from source
FROM golang:1.25.7-alpine3.23 AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/entrypoint

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian13 AS build-release-stage
WORKDIR /app
COPY --from=build-stage /usr/local/bin/entrypoint /usr/local/bin/entrypoint
EXPOSE 5000
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/entrypoint"]