FROM golang:1.25.7-alpine3.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/entrypoint

FROM alpine:3.23
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=builder /usr/local/bin/entrypoint /usr/local/bin/entrypoint
EXPOSE 5000
HEALTHCHECK --interval=30s --timeout=30s --retries=3 \ 
  CMD curl -f http://localhost:5000/health || exit 1
ENTRYPOINT ["/usr/local/bin/entrypoint"]