FROM golang:1.25.7-alpine3.23
WORKDIR /app
COPY go.mod go.sum ./
RUN apk add curl && go mod download && go mod verify

RUN CGO_ENABLED=0 GOOS=linux go build -o /opt/app
EXPOSE 5000
ENTRYPOINT ["/opt/app"]
HEALTHCHECK --interval=30s --timeout=30s --retries=3 \ 
  CMD curl -f http://localhost:5000/health || exit 1
